- hosts: amazon
  sudo: yes
  remote_user: ubuntu
  tasks:
  - name: Instalar paquetes 
    apt: name=python-setuptools state=present
    apt: name=build-essential state=present
    apt: name=python-dev state=present
    apt: name=git state=present
  - name: Obtener aplicacion de git
    command: git clone https://github.com/lorenmanu/submodulo-lorenzo.git
  - name: Permisos de ejecucion
    command: chmod -R +x submodulo-lorenzo
  - name: Instalar requisitos
    command: sudo pip install -r submodulo-lorenzo/requirements.txt
  - name: ejecutar
    command: nohup sudo python submodulo-lorenzo/manage.py runserver 0.0.0.0:80
